[project]
name = "braket-backend-blueqat"
version = "0.0.1"
description = "Braket backend for blueqat"
license = "Apache-2.0"
authors = "gyu-don <kato@blueqat.com>"

[build-system]
requires = ["blueqat>=0.4.2", "braket~=1.5.13"]
